## enable or disable automatic sync
auto_sync = true

## which search mode to use
search_mode = "fuzzy"

## which filter mode to use
filter_mode = "directory"

## which style to use
style = "compact"

workspaces = true
