auto_sync          = true
search_mode        = "fuzzy"
filter_mode        = "directory"
style              = "compact"
keymap_mode        = "vim-normal"

workspaces         = true

history_filter     = [
  "^curl",
  "^mc"
]

[stats]
common_subcommands = [
  "ls",
  "apt",
  "git",
  "go",
  "npm",
  "rm",
  "python",
  "python3",
  "tmux"
]

[sync]
records            = true
