# Zsh settings
export ZSH="$HOME/.oh-my-zsh"
export EDITOR="vi"
export BROWSER=termux-open-url

export GPG_TTY=$TTY
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

export GOPATH=$HOME/.go
export PATH="$HOME/.npm-global/bin:$GOPATH/bin:$HOME/.local/bin:$PATH"

export PIP_DISABLE_PIP_VERSION_CHECK=1
export VIRTUALENV_NO_PERIODIC_UPDATE=1

# ZSH_THEME="lambda-gitster"

plugins=(
    cp colored-man-pages command-not-found
    git jsontools ssh-agent z
)

zstyle :omz:plugins:ssh-agent quiet yes

autoload -U colors && colors

if [ -f $PREFIX/etc/bash_completion.d/git-prompt.sh ]; then
    source $PREFIX/etc/bash_completion.d/git-prompt.sh
fi

GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWCOLORHINTS=true

__last_status() {
    echo " %(?:%F{green}\$:%F{red}\$)%F{reset} "
}

__virtual_env() {
    if [ -n "${VIRTUAL_ENV}" ] && [ -z "${VIRTUAL_ENV_DISABLE_PROMPT:-}" ]; then
        if [ "$(basename $VIRTUAL_ENV)" = "__" ]; then
            echo "[$(basename $(dirname $VIRTUAL_ENV))] "
        else
            echo "($(basename $VIRTUAL_ENV)) "
        fi
    fi
}

precmd() {
    __git_ps1 "$(__virtual_env)%F{green}$(prompt)%F{reset}" "$(__last_status)" " (%s)"
    if [ -d .git -a ! -x .git/hooks/pre-commit -a -e .pre-commit-config.yaml ] && command -v pre-commit >&/dev/null; then
        pre-commit install --hook-type pre-commit
    fi
}

# PS1='%F{green}$(prompt)$(__git_ps1)%(?:%F{green} \$:%F{red} \$)%F{reset} '

source $ZSH/oh-my-zsh.sh

# User settings

# aliases
alias cp="nocorrect cp -v"
alias mv="nocorrect mv -v"
alias mkdir="nocorrect mkdir"
alias rm="rm -I"

alias ls="lsd"
alias la="ls -a"
alias lg="lazygit"
alias ll="ls -l"
alias lla="ls -la"
alias tree="ls --tree --icon never"

# direnv
eval "$(direnv hook zsh)"

# atuin
eval "$(atuin init zsh --disable-up-arrow)"

autoload -U bashcompinit
bashcompinit
PROG=tea _CLI_ZSH_AUTOCOMPLETE_HACK=1 source "/data/data/com.termux/files/home/.config/tea/autocomplete.zsh"
